name: ConfigDeploymentPolicy
description: 'Deployment Policy'
cli_alias: 'deployment-policy'
cmd_group: 'configuration'
rest_endpoint: '/mgmt/config/{domain}/ConfigDeploymentPolicy'
attributes:
  - name: Id
    tf_name: id
    path: name
    type: String
    required: true
    example: 'ConfigDeploymentPolicy_name'
    description: 'Name of the object. Must be unique among object types in application domain.'
  - name: AppDomain
    tf_name: app_domain
    type: String
    required: true
    example: 'test_domain'
    description: 'The name of the application domain the object belongs to'
  - name: UserSummary
    type: String
    description: 'Comments'
    cli_alias: summary
  - name: AcceptedConfig
    type: List
    element_type: String
    list_example:
      - '10.10.1.1/domainA/services/xslproxy?Name=foo.*'
    description: 'Accepted Configuration'
    cli_alias: accept
  - name: FilteredConfig
    type: List
    element_type: String
    list_example:
      - '10.10.1.1/domainA/services/xslproxy?Name=foo.*'
    description: 'Filtered Configuration'
    cli_alias: filter
  - name: ModifiedConfig
    type: List
    element_type: DmConfigModifyType
    description: 'Modified Configuration'
    cli_alias: modify
