name: DmDynamicParseSettingsReference
model_only: true
attributes:
- name: URL
  type: String
  description: Specifies a URL to a file that contains serialized XML or JSON properties
    to be merged into the dynamic object. These properties override any existing literal
    or default properties. The URL can contain variable references, and fields within
    the associated file can also contain variable references.
  test_value: '"some_url"'
  cli_alias: url
- name: Literal
  type: String
  example: literal
  description: Specifies a literal string that defines serialized XML or JSON properties
    for merging into the dynamic object. These properties override the existing default
    properties. The literal string can contain variable references.
  cli_alias: literal
- name: Default
  type: String
  reference_to: ParseSettings
  description: Specifies an existing object from which to retrieve default property
    values for the dynamic object. If an object is not specified, then the URL reference,
    the literal configuration, or the combination of URL reference and literal configuration
    fully define the action.
  cli_alias: default
