name: GWScriptSettings
description: 'GatewayScript Settings (`default` domain only)'
cli_alias: 'gatewayscript-settings'
cmd_group: 'system'
rest_endpoint: '/mgmt/config/default/GWScriptSettings/GatewayScript-Settings'
update_only: true
default_domain_only: true
attributes:
  - name: mAdminState
    tf_name: 'enabled'
    type: Bool
    bool_type: 'admin'
    default: true
    description: 'Administrative state'
    cli_alias: admin-state
  - name: UserSummary
    type: String
    description: 'Comments'
    cli_alias: summary
  - name: FrozenEnabled
    type: Bool
    default: true
    description: 'Freeze prototype'
    cli_alias: freeze-prototype
  - name: UntrustedCodeMitigated
    type: Bool
    default: true
    description: 'Untrusted code mitigation'
    cli_alias: untrusted-code-mitigations
  - name: ReloadNeeded
    type: Bool
    default: false
    description: 'System reload needed'
    cli_alias: reload-needed
    computed: true
  - name: TerminateTime
    type: Int64
    maximum: 300
    description: 'Max processing duration'
    cli_alias: max-processing-duration
