// Copyright © 2025 Scott Wiederhold <s.e.wiederhold@gmail.com>
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// This file is generated "gen/generator.go"
// !!CHANGES TO THIS FILE WILL BE OVERWRITTEN!!

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int32validator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/scottw514/terraform-provider-datapower/client"
)

type DatapowerProvider struct {
	version string
}

type DatapowerProviderModel struct {
	Hostname types.String `tfsdk:"hostname"`
	Port     types.Int32  `tfsdk:"port"`
	Username types.String `tfsdk:"username"`
	Password types.String `tfsdk:"password"`
	Insecure types.Bool   `tfsdk:"insecure"`
}

func (p *DatapowerProvider) Metadata(_ context.Context, _ provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "datapower"
	resp.Version = p.version
}

func (p *DatapowerProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"hostname": schema.StringAttribute{
				MarkdownDescription: "Hostname of the Datapower instance. Can be set via DP_HOSTNAME evnvironment variable. Defaults to `localhost`",
				Optional:            true,
			},
			"port": schema.Int32Attribute{
				MarkdownDescription: "Port for REST API calls. Can be set via DP_PORT evnvironment variable. Defaults to `5554`.",
				Optional:            true,
				Validators: []validator.Int32{
					int32validator.Between(1024, 65535),
				},
			},
			"username": schema.StringAttribute{
				MarkdownDescription: "Username for the Datapower instance. Can be set via DP_USERNAME evnvironment variable.",
				Optional:            true,
			},
			"password": schema.StringAttribute{
				MarkdownDescription: "Password for the Datapower instance. Can be set via DP_PASSWORD evnvironment variable.",
				Optional:            true,
				Sensitive:           true,
			},
			"insecure": schema.BoolAttribute{
				MarkdownDescription: "Allow insecure HTTPS client. Can be set via DP_INSECURE evnvironment variable. Defaults to `false`.",
				Optional:            true,
			},
		},
	}
}

func (p *DatapowerProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var config client.DatapowerClientConfig
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Create a new Datapower client and set it to the provider client
	c, err := client.NewClient(&config)
	if err != nil {
		resp.Diagnostics.AddError(
			"Client Error",
			"When creating datapower client: "+err.Error(),
		)
		return
	}

	resp.DataSourceData = &c
	resp.ResourceData = &c
}

func (p *DatapowerProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewFileResource,
		NewAAAJWTGeneratorResource,
		NewAAAJWTValidatorResource,
		NewAAAPolicyResource,
		NewAMQPBrokerResource,
		NewAMQPSourceProtocolHandlerResource,
		NewAPIApplicationTypeResource,
		NewAPIAuthURLRegistryResource,
		NewAPICORSResource,
		NewAPIClientIdentificationResource,
		NewAPICollectionResource,
		NewAPIConnectGatewayServiceResource,
		NewAPIDefinitionResource,
		NewAPIExecuteResource,
		NewAPIFinalResource,
		NewAPIGatewayResource,
		NewAPILDAPRegistryResource,
		NewAPIOperationResource,
		NewAPIPathResource,
		NewAPIPlanResource,
		NewAPIResultResource,
		NewAPIRoutingResource,
		NewAPIRuleResource,
		NewAPISchemaResource,
		NewAPISecurityResource,
		NewAPISecurityAPIKeyResource,
		NewAPISecurityBasicAuthResource,
		NewAPISecurityHTTPSchemeResource,
		NewAPISecurityOAuthResource,
		NewAPISecurityOAuthReqResource,
		NewAPISecurityRequirementResource,
		NewAPISecurityTokenManagerResource,
		NewAS1PollerSourceProtocolHandlerResource,
		NewAS2ProxySourceProtocolHandlerResource,
		NewAS2SourceProtocolHandlerResource,
		NewAS3SourceProtocolHandlerResource,
		NewAccessControlListResource,
		NewAccessProfileResource,
		NewAnalyticsEndpointResource,
		NewAppSecurityPolicyResource,
		NewAssemblyResource,
		NewAssemblyActionClientSecurityResource,
		NewAssemblyActionExtractResource,
		NewAssemblyActionFunctionCallResource,
		NewAssemblyActionGatewayScriptResource,
		NewAssemblyActionGraphQLCostAnalysisResource,
		NewAssemblyActionGraphQLExecuteResource,
		NewAssemblyActionGraphQLIntrospectResource,
		NewAssemblyActionHtmlPageResource,
		NewAssemblyActionInvokeResource,
		NewAssemblyActionJWTGenerateResource,
		NewAssemblyActionJWTValidateResource,
		NewAssemblyActionJson2XmlResource,
		NewAssemblyActionLogResource,
		NewAssemblyActionMapResource,
		NewAssemblyActionOAuthResource,
		NewAssemblyActionParseResource,
		NewAssemblyActionRateLimitResource,
		NewAssemblyActionRateLimitInfoResource,
		NewAssemblyActionRedactResource,
		NewAssemblyActionSetVarResource,
		NewAssemblyActionThrowResource,
		NewAssemblyActionUserSecurityResource,
		NewAssemblyActionValidateResource,
		NewAssemblyActionWSDLResource,
		NewAssemblyActionWebSocketUpgradeResource,
		NewAssemblyActionXSLTResource,
		NewAssemblyActionXml2JsonResource,
		NewAssemblyFunctionResource,
		NewAssemblyLogicOperationSwitchResource,
		NewAssemblyLogicSwitchResource,
		NewAuditLogResource,
		NewB2BCPAResource,
		NewB2BCPACollaborationResource,
		NewB2BCPAReceiverSettingResource,
		NewB2BCPASenderSettingResource,
		NewB2BGatewayResource,
		NewB2BPersistenceResource,
		NewB2BProfileResource,
		NewB2BProfileGroupResource,
		NewB2BXPathRoutingPolicyResource,
		NewCORSPolicyResource,
		NewCORSRuleResource,
		NewCRLFetchResource,
		NewCertMonitorResource,
		NewCompileOptionsPolicyResource,
		NewCompileSettingsResource,
		NewConfigDeploymentPolicyResource,
		NewConfigSequenceResource,
		NewConformancePolicyResource,
		NewControlListResource,
		NewCookieAttributePolicyResource,
		NewCountMonitorResource,
		NewCryptoCertificateResource,
		NewCryptoFWCredResource,
		NewCryptoIdentCredResource,
		NewCryptoKerberosKDCResource,
		NewCryptoKerberosKeytabResource,
		NewCryptoKeyResource,
		NewCryptoSSKeyResource,
		NewCryptoValCredResource,
		NewDNSNameServiceResource,
		NewDeploymentPolicyParametersBindingResource,
		NewDistributedVariableResource,
		NewDocumentCryptoMapResource,
		NewDomainResource,
		NewDomainAvailabilityResource,
		NewDomainSettingsResource,
		NewDurationMonitorResource,
		NewEBMS2SourceProtocolHandlerResource,
		NewEBMS3SourceProtocolHandlerResource,
		NewErrorReportSettingsResource,
		NewFTPFilePollerSourceProtocolHandlerResource,
		NewFTPQuoteCommandsResource,
		NewFTPServerSourceProtocolHandlerResource,
		NewFileSystemUsageMonitorResource,
		NewFilterActionResource,
		NewFormsLoginPolicyResource,
		NewGWSRemoteDebugResource,
		NewGWScriptSettingsResource,
		NewGatewayPeeringResource,
		NewGatewayPeeringGroupResource,
		NewGatewayPeeringManagerResource,
		NewGitOpsResource,
		NewGitOpsTemplateResource,
		NewGitOpsVariablesResource,
		NewGraphQLSchemaOptionsResource,
		NewHTTPInputConversionMapResource,
		NewHTTPSSourceProtocolHandlerResource,
		NewHTTPSourceProtocolHandlerResource,
		NewHTTPUserAgentResource,
		NewHostAliasResource,
		NewImportPackageResource,
		NewIncludeConfigResource,
		NewInteropServiceResource,
		NewJOSERecipientIdentifierResource,
		NewJOSESignatureIdentifierResource,
		NewJSONSettingsResource,
		NewJWEHeaderResource,
		NewJWERecipientResource,
		NewJWSSignatureResource,
		NewKafkaClusterResource,
		NewKafkaSourceProtocolHandlerResource,
		NewLDAPConnectionPoolResource,
		NewLDAPSearchParametersResource,
		NewLoadBalancerGroupResource,
		NewLogLabelResource,
		NewLogTargetResource,
		NewLunaResource,
		NewLunaHAGroupResource,
		NewLunaHASettingsResource,
		NewLunaPartitionResource,
		NewMCFCustomRuleResource,
		NewMCFHttpHeaderResource,
		NewMCFHttpMethodResource,
		NewMCFHttpURLResource,
		NewMCFXPathResource,
		NewMPGWErrorActionResource,
		NewMPGWErrorHandlingPolicyResource,
		NewMQManagerResource,
		NewMQManagerGroupResource,
		NewMQv9PlusMFTSourceProtocolHandlerResource,
		NewMQv9PlusSourceProtocolHandlerResource,
		NewMTOMPolicyResource,
		NewMatchingResource,
		NewMessageContentFiltersResource,
		NewMessageMatchingResource,
		NewMessageTypeResource,
		NewMgmtInterfaceResource,
		NewMultiProtocolGatewayResource,
		NewNFSClientSettingsResource,
		NewNFSDynamicMountsResource,
		NewNFSFilePollerSourceProtocolHandlerResource,
		NewNFSStaticMountResource,
		NewNameValueProfileResource,
		NewOAuthProviderSettingsResource,
		NewOAuthSupportedClientResource,
		NewOAuthSupportedClientGroupResource,
		NewODRResource,
		NewODRConnectorGroupResource,
		NewOpenTelemetryResource,
		NewOpenTelemetryExporterResource,
		NewOpenTelemetrySamplerResource,
		NewOperationRateLimitResource,
		NewPOPPollerSourceProtocolHandlerResource,
		NewParseSettingsResource,
		NewPasswordAliasResource,
		NewPeerGroupResource,
		NewPolicyAttachmentsResource,
		NewPolicyParametersResource,
		NewProbeResource,
		NewProcessingMetadataResource,
		NewQuotaEnforcementServerResource,
		NewRADIUSSettingsResource,
		NewRBMSettingsResource,
		NewRaidVolumeResource,
		NewRateLimitConfigurationResource,
		NewRateLimitDefinitionResource,
		NewRateLimitDefinitionGroupResource,
		NewSAMLAttributesResource,
		NewSFTPFilePollerSourceProtocolHandlerResource,
		NewSLMActionResource,
		NewSLMCredClassResource,
		NewSLMPolicyResource,
		NewSLMRsrcClassResource,
		NewSLMScheduleResource,
		NewSMTPServerConnectionResource,
		NewSNMPSettingsResource,
		NewSOAPHeaderDispositionResource,
		NewSQLDataSourceResource,
		NewSSHClientProfileResource,
		NewSSHDomainClientProfileResource,
		NewSSHServerProfileResource,
		NewSSHServerSourceProtocolHandlerResource,
		NewSSHServiceResource,
		NewSSLClientProfileResource,
		NewSSLProxyServiceResource,
		NewSSLSNIMappingResource,
		NewSSLSNIServerProfileResource,
		NewSSLServerProfileResource,
		NewSchemaExceptionMapResource,
		NewSecureBackupModeResource,
		NewSocialLoginPolicyResource,
		NewStatelessTCPSourceProtocolHandlerResource,
		NewStatisticsResource,
		NewStylePolicyResource,
		NewStylePolicyActionResource,
		NewStylePolicyRuleResource,
		NewSystemSettingsResource,
		NewTAMResource,
		NewTCPProxyServiceResource,
		NewThrottlerResource,
		NewTimeSettingsResource,
		NewURLMapResource,
		NewURLRefreshPolicyResource,
		NewURLRewritePolicyResource,
		NewUserResource,
		NewUserGroupResource,
		NewVisibilityListResource,
		NewWCCServiceResource,
		NewWSEndpointRewritePolicyResource,
		NewWSGatewayResource,
		NewWSRRSavedSearchSubscriptionResource,
		NewWSRRServerResource,
		NewWSRRSubscriptionResource,
		NewWSStylePolicyResource,
		NewWSStylePolicyRuleResource,
		NewWXSGridResource,
		NewWebAppErrorHandlingPolicyResource,
		NewWebAppFWResource,
		NewWebAppRequestResource,
		NewWebAppResponseResource,
		NewWebAppSessionPolicyResource,
		NewWebB2BViewerResource,
		NewWebGUIResource,
		NewWebServiceMonitorResource,
		NewWebServicesAgentResource,
		NewWebSphereJMSServerResource,
		NewWebSphereJMSSourceProtocolHandlerResource,
		NewWebTokenServiceResource,
		NewXACMLPDPResource,
		NewXMLFirewallServiceResource,
		NewXMLManagerResource,
		NewXPathRoutingMapResource,
		NewXSLCoprocServiceResource,
		NewXSLProxyServiceResource,
		NewXTCProtocolHandlerResource,
		NewZosNSSClientResource,
	}
}

func (p *DatapowerProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewAAAJWTGeneratorDataSource,
		NewAAAJWTValidatorDataSource,
		NewAAAPolicyDataSource,
		NewAMQPBrokerDataSource,
		NewAMQPSourceProtocolHandlerDataSource,
		NewAPIApplicationTypeDataSource,
		NewAPIAuthURLRegistryDataSource,
		NewAPICORSDataSource,
		NewAPIClientIdentificationDataSource,
		NewAPICollectionDataSource,
		NewAPIConnectGatewayServiceDataSource,
		NewAPIDefinitionDataSource,
		NewAPIExecuteDataSource,
		NewAPIFinalDataSource,
		NewAPIGatewayDataSource,
		NewAPILDAPRegistryDataSource,
		NewAPIOperationDataSource,
		NewAPIPathDataSource,
		NewAPIPlanDataSource,
		NewAPIResultDataSource,
		NewAPIRoutingDataSource,
		NewAPIRuleDataSource,
		NewAPISchemaDataSource,
		NewAPISecurityDataSource,
		NewAPISecurityAPIKeyDataSource,
		NewAPISecurityBasicAuthDataSource,
		NewAPISecurityHTTPSchemeDataSource,
		NewAPISecurityOAuthDataSource,
		NewAPISecurityOAuthReqDataSource,
		NewAPISecurityRequirementDataSource,
		NewAPISecurityTokenManagerDataSource,
		NewAS1PollerSourceProtocolHandlerDataSource,
		NewAS2ProxySourceProtocolHandlerDataSource,
		NewAS2SourceProtocolHandlerDataSource,
		NewAS3SourceProtocolHandlerDataSource,
		NewAccessControlListDataSource,
		NewAccessProfileDataSource,
		NewAnalyticsEndpointDataSource,
		NewAppSecurityPolicyDataSource,
		NewAssemblyDataSource,
		NewAssemblyActionClientSecurityDataSource,
		NewAssemblyActionExtractDataSource,
		NewAssemblyActionFunctionCallDataSource,
		NewAssemblyActionGatewayScriptDataSource,
		NewAssemblyActionGraphQLCostAnalysisDataSource,
		NewAssemblyActionGraphQLExecuteDataSource,
		NewAssemblyActionGraphQLIntrospectDataSource,
		NewAssemblyActionHtmlPageDataSource,
		NewAssemblyActionInvokeDataSource,
		NewAssemblyActionJWTGenerateDataSource,
		NewAssemblyActionJWTValidateDataSource,
		NewAssemblyActionJson2XmlDataSource,
		NewAssemblyActionLogDataSource,
		NewAssemblyActionMapDataSource,
		NewAssemblyActionOAuthDataSource,
		NewAssemblyActionParseDataSource,
		NewAssemblyActionRateLimitDataSource,
		NewAssemblyActionRateLimitInfoDataSource,
		NewAssemblyActionRedactDataSource,
		NewAssemblyActionSetVarDataSource,
		NewAssemblyActionThrowDataSource,
		NewAssemblyActionUserSecurityDataSource,
		NewAssemblyActionValidateDataSource,
		NewAssemblyActionWSDLDataSource,
		NewAssemblyActionWebSocketUpgradeDataSource,
		NewAssemblyActionXSLTDataSource,
		NewAssemblyActionXml2JsonDataSource,
		NewAssemblyFunctionDataSource,
		NewAssemblyLogicOperationSwitchDataSource,
		NewAssemblyLogicSwitchDataSource,
		NewAuditLogDataSource,
		NewB2BCPADataSource,
		NewB2BCPACollaborationDataSource,
		NewB2BCPAReceiverSettingDataSource,
		NewB2BCPASenderSettingDataSource,
		NewB2BGatewayDataSource,
		NewB2BPersistenceDataSource,
		NewB2BProfileDataSource,
		NewB2BProfileGroupDataSource,
		NewB2BXPathRoutingPolicyDataSource,
		NewCORSPolicyDataSource,
		NewCORSRuleDataSource,
		NewCRLFetchDataSource,
		NewCertMonitorDataSource,
		NewCompileOptionsPolicyDataSource,
		NewCompileSettingsDataSource,
		NewConfigDeploymentPolicyDataSource,
		NewConfigSequenceDataSource,
		NewConformancePolicyDataSource,
		NewControlListDataSource,
		NewCookieAttributePolicyDataSource,
		NewCountMonitorDataSource,
		NewCryptoCertificateDataSource,
		NewCryptoFWCredDataSource,
		NewCryptoIdentCredDataSource,
		NewCryptoKerberosKDCDataSource,
		NewCryptoKerberosKeytabDataSource,
		NewCryptoKeyDataSource,
		NewCryptoSSKeyDataSource,
		NewCryptoValCredDataSource,
		NewDNSNameServiceDataSource,
		NewDeploymentPolicyParametersBindingDataSource,
		NewDistributedVariableDataSource,
		NewDocumentCryptoMapDataSource,
		NewDomainDataSource,
		NewDomainAvailabilityDataSource,
		NewDomainSettingsDataSource,
		NewDurationMonitorDataSource,
		NewEBMS2SourceProtocolHandlerDataSource,
		NewEBMS3SourceProtocolHandlerDataSource,
		NewErrorReportSettingsDataSource,
		NewFTPFilePollerSourceProtocolHandlerDataSource,
		NewFTPQuoteCommandsDataSource,
		NewFTPServerSourceProtocolHandlerDataSource,
		NewFileSystemUsageMonitorDataSource,
		NewFilterActionDataSource,
		NewFormsLoginPolicyDataSource,
		NewGWSRemoteDebugDataSource,
		NewGWScriptSettingsDataSource,
		NewGatewayPeeringDataSource,
		NewGatewayPeeringGroupDataSource,
		NewGatewayPeeringManagerDataSource,
		NewGitOpsDataSource,
		NewGitOpsTemplateDataSource,
		NewGitOpsVariablesDataSource,
		NewGraphQLSchemaOptionsDataSource,
		NewHTTPInputConversionMapDataSource,
		NewHTTPSSourceProtocolHandlerDataSource,
		NewHTTPSourceProtocolHandlerDataSource,
		NewHTTPUserAgentDataSource,
		NewHostAliasDataSource,
		NewImportPackageDataSource,
		NewIncludeConfigDataSource,
		NewInteropServiceDataSource,
		NewJOSERecipientIdentifierDataSource,
		NewJOSESignatureIdentifierDataSource,
		NewJSONSettingsDataSource,
		NewJWEHeaderDataSource,
		NewJWERecipientDataSource,
		NewJWSSignatureDataSource,
		NewKafkaClusterDataSource,
		NewKafkaSourceProtocolHandlerDataSource,
		NewLDAPConnectionPoolDataSource,
		NewLDAPSearchParametersDataSource,
		NewLoadBalancerGroupDataSource,
		NewLogLabelDataSource,
		NewLogTargetDataSource,
		NewLunaDataSource,
		NewLunaHAGroupDataSource,
		NewLunaHASettingsDataSource,
		NewLunaPartitionDataSource,
		NewMCFCustomRuleDataSource,
		NewMCFHttpHeaderDataSource,
		NewMCFHttpMethodDataSource,
		NewMCFHttpURLDataSource,
		NewMCFXPathDataSource,
		NewMPGWErrorActionDataSource,
		NewMPGWErrorHandlingPolicyDataSource,
		NewMQManagerDataSource,
		NewMQManagerGroupDataSource,
		NewMQv9PlusMFTSourceProtocolHandlerDataSource,
		NewMQv9PlusSourceProtocolHandlerDataSource,
		NewMTOMPolicyDataSource,
		NewMatchingDataSource,
		NewMessageContentFiltersDataSource,
		NewMessageMatchingDataSource,
		NewMessageTypeDataSource,
		NewMgmtInterfaceDataSource,
		NewMultiProtocolGatewayDataSource,
		NewNFSClientSettingsDataSource,
		NewNFSDynamicMountsDataSource,
		NewNFSFilePollerSourceProtocolHandlerDataSource,
		NewNFSStaticMountDataSource,
		NewNameValueProfileDataSource,
		NewOAuthProviderSettingsDataSource,
		NewOAuthSupportedClientDataSource,
		NewOAuthSupportedClientGroupDataSource,
		NewODRDataSource,
		NewODRConnectorGroupDataSource,
		NewOpenTelemetryDataSource,
		NewOpenTelemetryExporterDataSource,
		NewOpenTelemetrySamplerDataSource,
		NewOperationRateLimitDataSource,
		NewPOPPollerSourceProtocolHandlerDataSource,
		NewParseSettingsDataSource,
		NewPasswordAliasDataSource,
		NewPeerGroupDataSource,
		NewPolicyAttachmentsDataSource,
		NewPolicyParametersDataSource,
		NewProbeDataSource,
		NewProcessingMetadataDataSource,
		NewQuotaEnforcementServerDataSource,
		NewRADIUSSettingsDataSource,
		NewRBMSettingsDataSource,
		NewRaidVolumeDataSource,
		NewRateLimitConfigurationDataSource,
		NewRateLimitDefinitionDataSource,
		NewRateLimitDefinitionGroupDataSource,
		NewSAMLAttributesDataSource,
		NewSFTPFilePollerSourceProtocolHandlerDataSource,
		NewSLMActionDataSource,
		NewSLMCredClassDataSource,
		NewSLMPolicyDataSource,
		NewSLMRsrcClassDataSource,
		NewSLMScheduleDataSource,
		NewSMTPServerConnectionDataSource,
		NewSNMPSettingsDataSource,
		NewSOAPHeaderDispositionDataSource,
		NewSQLDataSourceDataSource,
		NewSSHClientProfileDataSource,
		NewSSHDomainClientProfileDataSource,
		NewSSHServerProfileDataSource,
		NewSSHServerSourceProtocolHandlerDataSource,
		NewSSHServiceDataSource,
		NewSSLClientProfileDataSource,
		NewSSLProxyServiceDataSource,
		NewSSLSNIMappingDataSource,
		NewSSLSNIServerProfileDataSource,
		NewSSLServerProfileDataSource,
		NewSchemaExceptionMapDataSource,
		NewSecureBackupModeDataSource,
		NewSocialLoginPolicyDataSource,
		NewStatelessTCPSourceProtocolHandlerDataSource,
		NewStatisticsDataSource,
		NewStylePolicyDataSource,
		NewStylePolicyActionDataSource,
		NewStylePolicyRuleDataSource,
		NewSystemSettingsDataSource,
		NewTAMDataSource,
		NewTCPProxyServiceDataSource,
		NewThrottlerDataSource,
		NewTimeSettingsDataSource,
		NewURLMapDataSource,
		NewURLRefreshPolicyDataSource,
		NewURLRewritePolicyDataSource,
		NewUserDataSource,
		NewUserGroupDataSource,
		NewVisibilityListDataSource,
		NewWCCServiceDataSource,
		NewWSEndpointRewritePolicyDataSource,
		NewWSGatewayDataSource,
		NewWSRRSavedSearchSubscriptionDataSource,
		NewWSRRServerDataSource,
		NewWSRRSubscriptionDataSource,
		NewWSStylePolicyDataSource,
		NewWSStylePolicyRuleDataSource,
		NewWXSGridDataSource,
		NewWebAppErrorHandlingPolicyDataSource,
		NewWebAppFWDataSource,
		NewWebAppRequestDataSource,
		NewWebAppResponseDataSource,
		NewWebAppSessionPolicyDataSource,
		NewWebB2BViewerDataSource,
		NewWebGUIDataSource,
		NewWebServiceMonitorDataSource,
		NewWebServicesAgentDataSource,
		NewWebSphereJMSServerDataSource,
		NewWebSphereJMSSourceProtocolHandlerDataSource,
		NewWebTokenServiceDataSource,
		NewXACMLPDPDataSource,
		NewXMLFirewallServiceDataSource,
		NewXMLManagerDataSource,
		NewXPathRoutingMapDataSource,
		NewXSLCoprocServiceDataSource,
		NewXSLProxyServiceDataSource,
		NewXTCProtocolHandlerDataSource,
		NewZosNSSClientDataSource,
	}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &DatapowerProvider{
			version: version,
		}
	}
}
