// Copyright © 2025 Scott Wiederhold <s.e.wiederhold@gmail.com>
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// This file is generated "gen/generator.go"
// !!CHANGES TO THIS FILE WILL BE OVERWRITTEN!!

package provider

import (
	"context"
	"regexp"
	"sync"

	"github.com/hashicorp/terraform-plugin-framework-validators/int32validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/mapvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/scottw514/terraform-provider-datapower/client"
	"github.com/scottw514/terraform-provider-datapower/internal/provider/actions"
	"github.com/scottw514/terraform-provider-datapower/internal/provider/datasources"
	"github.com/scottw514/terraform-provider-datapower/internal/provider/resources"
	"github.com/scottw514/terraform-provider-datapower/internal/provider/tfutils"
	"github.com/scottw514/terraform-provider-datapower/internal/provider/validators"
)

type DatapowerProvider struct {
	version string
}

type DatapowerProviderTargetsModel struct {
	Hostname types.String `tfsdk:"hostname"`
	Port     types.Int32  `tfsdk:"port"`
	Username types.String `tfsdk:"username"`
	Password types.String `tfsdk:"password"`
	Insecure types.Bool   `tfsdk:"insecure"`
}

type DatapowerProviderModel struct {
	Hostname types.String                              `tfsdk:"hostname"`
	Port     types.Int32                               `tfsdk:"port"`
	Username types.String                              `tfsdk:"username"`
	Password types.String                              `tfsdk:"password"`
	Insecure types.Bool                                `tfsdk:"insecure"`
	Targets  map[string]*DatapowerProviderTargetsModel `tfsdk:"targets"`
}

func (p *DatapowerProvider) Metadata(_ context.Context, _ provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "datapower"
	resp.Version = p.version
}

func (p *DatapowerProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"hostname": schema.StringAttribute{
				MarkdownDescription: "Hostname of the Datapower instance. Can be set via DP_HOSTNAME evnvironment variable. Defaults to `localhost`",
				Optional:            true,
			},
			"port": schema.Int32Attribute{
				MarkdownDescription: "Port for REST API calls. Can be set via DP_PORT evnvironment variable. Defaults to `5554`.",
				Optional:            true,
				Validators: []validator.Int32{
					int32validator.Between(1024, 65535),
				},
			},
			"username": schema.StringAttribute{
				MarkdownDescription: "Username for the Datapower instance. Can be set via DP_USERNAME evnvironment variable.",
				Optional:            true,
			},
			"password": schema.StringAttribute{
				MarkdownDescription: "Password for the Datapower instance. Can be set via DP_PASSWORD evnvironment variable.",
				Optional:            true,
				Sensitive:           true,
			},
			"insecure": schema.BoolAttribute{
				MarkdownDescription: "Allow insecure HTTPS client. Can be set via DP_INSECURE evnvironment variable. Defaults to `false`.",
				Optional:            true,
			},
			"targets": schema.MapNestedAttribute{
				Description: "Map of available target hosts. The map key value is assigned to `provider_target` on `resource` or `datasource` blocks. Top levels values will be used for any unset attributes on the target.",
				Optional:    true,
				Validators: []validator.Map{
					validators.NoReservedTargetName(),
					mapvalidator.KeysAre(
						stringvalidator.LengthAtLeast(1),
						stringvalidator.RegexMatches(
							regexp.MustCompile(`^[a-zA-Z0-9_-]+$`),
							"Target names must contain only letters, numbers, hyphens, and underscores",
						),
					),
				},
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"hostname": schema.StringAttribute{
							MarkdownDescription: "Hostname or IP address of the target.",
							Required:            true,
						},
						"port": schema.Int32Attribute{
							MarkdownDescription: "Port for REST API calls. Defaults to `5554`.",
							Optional:            true,
							Validators: []validator.Int32{
								int32validator.Between(1024, 65535),
							},
						},
						"username": schema.StringAttribute{
							MarkdownDescription: "Username for the target. If unset, will use the top level `username` or evnvironment variable.",
							Optional:            true,
						},
						"password": schema.StringAttribute{
							MarkdownDescription: "Password for the target. If unset, will use the top level `password` or evnvironment variable.",
							Optional:            true,
							Sensitive:           true,
						},
						"insecure": schema.BoolAttribute{
							MarkdownDescription: "Allow insecure HTTPS client. If unset, will use the top level `insecure` or evnvironment variable.",
							Optional:            true,
						},
					},
				},
			},
		},
	}
}

func (p *DatapowerProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var config client.DatapowerClientConfig
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Create a new Datapower client and set it to the provider client
	c, err := client.NewClient(&config)
	if err != nil {
		resp.Diagnostics.AddError(
			"Client Error",
			"When creating datapower client: "+err.Error(),
		)
		return
	}

	data := tfutils.ProviderData{
		Client: c,
		Mu:     sync.Mutex{},
	}
	resp.DataSourceData = &data
	resp.ResourceData = &data
	actions.Process.Provider = &data
}

func (p *DatapowerProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		resources.NewFileResource,
		resources.NewAAAJWTGeneratorResource,
		resources.NewAAAJWTValidatorResource,
		resources.NewAAAPolicyResource,
		resources.NewAMQPBrokerResource,
		resources.NewAMQPSourceProtocolHandlerResource,
		resources.NewAPIApplicationTypeResource,
		resources.NewAPIAuthURLRegistryResource,
		resources.NewAPICORSResource,
		resources.NewAPIClientIdentificationResource,
		resources.NewAPICollectionResource,
		resources.NewAPIConnectGatewayServiceResource,
		resources.NewAPIDefinitionResource,
		resources.NewAPIExecuteResource,
		resources.NewAPIFinalResource,
		resources.NewAPIGatewayResource,
		resources.NewAPILDAPRegistryResource,
		resources.NewAPIOperationResource,
		resources.NewAPIPathResource,
		resources.NewAPIPlanResource,
		resources.NewAPIResultResource,
		resources.NewAPIRoutingResource,
		resources.NewAPIRuleResource,
		resources.NewAPISchemaResource,
		resources.NewAPISecurityResource,
		resources.NewAPISecurityAPIKeyResource,
		resources.NewAPISecurityBasicAuthResource,
		resources.NewAPISecurityHTTPSchemeResource,
		resources.NewAPISecurityOAuthResource,
		resources.NewAPISecurityOAuthReqResource,
		resources.NewAPISecurityRequirementResource,
		resources.NewAPISecurityTokenManagerResource,
		resources.NewAS1PollerSourceProtocolHandlerResource,
		resources.NewAS2ProxySourceProtocolHandlerResource,
		resources.NewAS2SourceProtocolHandlerResource,
		resources.NewAS3SourceProtocolHandlerResource,
		resources.NewAccessControlListResource,
		resources.NewAccessProfileResource,
		resources.NewAnalyticsEndpointResource,
		resources.NewAppSecurityPolicyResource,
		resources.NewAssemblyResource,
		resources.NewAssemblyActionClientSecurityResource,
		resources.NewAssemblyActionExtractResource,
		resources.NewAssemblyActionFunctionCallResource,
		resources.NewAssemblyActionGatewayScriptResource,
		resources.NewAssemblyActionGraphQLCostAnalysisResource,
		resources.NewAssemblyActionGraphQLExecuteResource,
		resources.NewAssemblyActionGraphQLIntrospectResource,
		resources.NewAssemblyActionHtmlPageResource,
		resources.NewAssemblyActionInvokeResource,
		resources.NewAssemblyActionJWTGenerateResource,
		resources.NewAssemblyActionJWTValidateResource,
		resources.NewAssemblyActionJson2XmlResource,
		resources.NewAssemblyActionLogResource,
		resources.NewAssemblyActionMapResource,
		resources.NewAssemblyActionOAuthResource,
		resources.NewAssemblyActionParseResource,
		resources.NewAssemblyActionRateLimitResource,
		resources.NewAssemblyActionRateLimitInfoResource,
		resources.NewAssemblyActionRedactResource,
		resources.NewAssemblyActionSetVarResource,
		resources.NewAssemblyActionThrowResource,
		resources.NewAssemblyActionUserSecurityResource,
		resources.NewAssemblyActionValidateResource,
		resources.NewAssemblyActionWSDLResource,
		resources.NewAssemblyActionWebSocketUpgradeResource,
		resources.NewAssemblyActionXSLTResource,
		resources.NewAssemblyActionXml2JsonResource,
		resources.NewAssemblyFunctionResource,
		resources.NewAssemblyLogicOperationSwitchResource,
		resources.NewAssemblyLogicSwitchResource,
		resources.NewAuditLogResource,
		resources.NewB2BCPAResource,
		resources.NewB2BCPACollaborationResource,
		resources.NewB2BCPAReceiverSettingResource,
		resources.NewB2BCPASenderSettingResource,
		resources.NewB2BGatewayResource,
		resources.NewB2BPersistenceResource,
		resources.NewB2BProfileResource,
		resources.NewB2BProfileGroupResource,
		resources.NewB2BXPathRoutingPolicyResource,
		resources.NewCORSPolicyResource,
		resources.NewCORSRuleResource,
		resources.NewCRLFetchResource,
		resources.NewCertMonitorResource,
		resources.NewCompileOptionsPolicyResource,
		resources.NewCompileSettingsResource,
		resources.NewConfigDeploymentPolicyResource,
		resources.NewConfigSequenceResource,
		resources.NewConformancePolicyResource,
		resources.NewControlListResource,
		resources.NewCookieAttributePolicyResource,
		resources.NewCountMonitorResource,
		resources.NewCryptoCertificateResource,
		resources.NewCryptoFWCredResource,
		resources.NewCryptoIdentCredResource,
		resources.NewCryptoKerberosKDCResource,
		resources.NewCryptoKerberosKeytabResource,
		resources.NewCryptoKeyResource,
		resources.NewCryptoSSKeyResource,
		resources.NewCryptoValCredResource,
		resources.NewDNSNameServiceResource,
		resources.NewDeploymentPolicyParametersBindingResource,
		resources.NewDistributedVariableResource,
		resources.NewDocumentCryptoMapResource,
		resources.NewDomainResource,
		resources.NewDomainAvailabilityResource,
		resources.NewDomainSettingsResource,
		resources.NewDurationMonitorResource,
		resources.NewEBMS2SourceProtocolHandlerResource,
		resources.NewEBMS3SourceProtocolHandlerResource,
		resources.NewErrorReportSettingsResource,
		resources.NewFTPFilePollerSourceProtocolHandlerResource,
		resources.NewFTPQuoteCommandsResource,
		resources.NewFTPServerSourceProtocolHandlerResource,
		resources.NewFileSystemUsageMonitorResource,
		resources.NewFilterActionResource,
		resources.NewFormsLoginPolicyResource,
		resources.NewGWSRemoteDebugResource,
		resources.NewGWScriptSettingsResource,
		resources.NewGatewayPeeringResource,
		resources.NewGatewayPeeringGroupResource,
		resources.NewGatewayPeeringManagerResource,
		resources.NewGitOpsResource,
		resources.NewGitOpsTemplateResource,
		resources.NewGitOpsVariablesResource,
		resources.NewGraphQLSchemaOptionsResource,
		resources.NewHTTPInputConversionMapResource,
		resources.NewHTTPSSourceProtocolHandlerResource,
		resources.NewHTTPSourceProtocolHandlerResource,
		resources.NewHTTPUserAgentResource,
		resources.NewHostAliasResource,
		resources.NewImportPackageResource,
		resources.NewIncludeConfigResource,
		resources.NewInteropServiceResource,
		resources.NewJOSERecipientIdentifierResource,
		resources.NewJOSESignatureIdentifierResource,
		resources.NewJSONSettingsResource,
		resources.NewJWEHeaderResource,
		resources.NewJWERecipientResource,
		resources.NewJWSSignatureResource,
		resources.NewKafkaClusterResource,
		resources.NewKafkaSourceProtocolHandlerResource,
		resources.NewLDAPConnectionPoolResource,
		resources.NewLDAPSearchParametersResource,
		resources.NewLoadBalancerGroupResource,
		resources.NewLogLabelResource,
		resources.NewLogTargetResource,
		resources.NewLunaResource,
		resources.NewLunaHAGroupResource,
		resources.NewLunaHASettingsResource,
		resources.NewLunaPartitionResource,
		resources.NewMCFCustomRuleResource,
		resources.NewMCFHttpHeaderResource,
		resources.NewMCFHttpMethodResource,
		resources.NewMCFHttpURLResource,
		resources.NewMCFXPathResource,
		resources.NewMPGWErrorActionResource,
		resources.NewMPGWErrorHandlingPolicyResource,
		resources.NewMQManagerResource,
		resources.NewMQManagerGroupResource,
		resources.NewMQv9PlusMFTSourceProtocolHandlerResource,
		resources.NewMQv9PlusSourceProtocolHandlerResource,
		resources.NewMTOMPolicyResource,
		resources.NewMatchingResource,
		resources.NewMessageContentFiltersResource,
		resources.NewMessageMatchingResource,
		resources.NewMessageTypeResource,
		resources.NewMgmtInterfaceResource,
		resources.NewMultiProtocolGatewayResource,
		resources.NewNFSClientSettingsResource,
		resources.NewNFSDynamicMountsResource,
		resources.NewNFSFilePollerSourceProtocolHandlerResource,
		resources.NewNFSStaticMountResource,
		resources.NewNameValueProfileResource,
		resources.NewOAuthProviderSettingsResource,
		resources.NewOAuthSupportedClientResource,
		resources.NewOAuthSupportedClientGroupResource,
		resources.NewODRResource,
		resources.NewODRConnectorGroupResource,
		resources.NewOpenTelemetryResource,
		resources.NewOpenTelemetryExporterResource,
		resources.NewOpenTelemetrySamplerResource,
		resources.NewOperationRateLimitResource,
		resources.NewPOPPollerSourceProtocolHandlerResource,
		resources.NewParseSettingsResource,
		resources.NewPasswordAliasResource,
		resources.NewPeerGroupResource,
		resources.NewPolicyAttachmentsResource,
		resources.NewPolicyParametersResource,
		resources.NewProbeResource,
		resources.NewProcessingMetadataResource,
		resources.NewQuotaEnforcementServerResource,
		resources.NewRADIUSSettingsResource,
		resources.NewRBMSettingsResource,
		resources.NewRaidVolumeResource,
		resources.NewRateLimitConfigurationResource,
		resources.NewRateLimitDefinitionResource,
		resources.NewRateLimitDefinitionGroupResource,
		resources.NewSAMLAttributesResource,
		resources.NewSFTPFilePollerSourceProtocolHandlerResource,
		resources.NewSLMActionResource,
		resources.NewSLMCredClassResource,
		resources.NewSLMPolicyResource,
		resources.NewSLMRsrcClassResource,
		resources.NewSLMScheduleResource,
		resources.NewSMTPServerConnectionResource,
		resources.NewSNMPSettingsResource,
		resources.NewSOAPHeaderDispositionResource,
		resources.NewSQLDataSourceResource,
		resources.NewSSHClientProfileResource,
		resources.NewSSHDomainClientProfileResource,
		resources.NewSSHServerProfileResource,
		resources.NewSSHServerSourceProtocolHandlerResource,
		resources.NewSSHServiceResource,
		resources.NewSSLClientProfileResource,
		resources.NewSSLProxyServiceResource,
		resources.NewSSLSNIMappingResource,
		resources.NewSSLSNIServerProfileResource,
		resources.NewSSLServerProfileResource,
		resources.NewSchemaExceptionMapResource,
		resources.NewSecureBackupModeResource,
		resources.NewSocialLoginPolicyResource,
		resources.NewStatelessTCPSourceProtocolHandlerResource,
		resources.NewStatisticsResource,
		resources.NewStylePolicyResource,
		resources.NewStylePolicyActionResource,
		resources.NewStylePolicyRuleResource,
		resources.NewSystemSettingsResource,
		resources.NewTAMResource,
		resources.NewTCPProxyServiceResource,
		resources.NewThrottlerResource,
		resources.NewTimeSettingsResource,
		resources.NewURLMapResource,
		resources.NewURLRefreshPolicyResource,
		resources.NewURLRewritePolicyResource,
		resources.NewUserResource,
		resources.NewUserGroupResource,
		resources.NewVisibilityListResource,
		resources.NewWCCServiceResource,
		resources.NewWSEndpointRewritePolicyResource,
		resources.NewWSGatewayResource,
		resources.NewWSRRSavedSearchSubscriptionResource,
		resources.NewWSRRServerResource,
		resources.NewWSRRSubscriptionResource,
		resources.NewWSStylePolicyResource,
		resources.NewWSStylePolicyRuleResource,
		resources.NewWXSGridResource,
		resources.NewWebAppErrorHandlingPolicyResource,
		resources.NewWebAppFWResource,
		resources.NewWebAppRequestResource,
		resources.NewWebAppResponseResource,
		resources.NewWebAppSessionPolicyResource,
		resources.NewWebB2BViewerResource,
		resources.NewWebGUIResource,
		resources.NewWebServiceMonitorResource,
		resources.NewWebServicesAgentResource,
		resources.NewWebSphereJMSServerResource,
		resources.NewWebSphereJMSSourceProtocolHandlerResource,
		resources.NewWebTokenServiceResource,
		resources.NewXACMLPDPResource,
		resources.NewXMLFirewallServiceResource,
		resources.NewXMLManagerResource,
		resources.NewXPathRoutingMapResource,
		resources.NewXSLCoprocServiceResource,
		resources.NewXSLProxyServiceResource,
		resources.NewXTCProtocolHandlerResource,
		resources.NewZosNSSClientResource,
	}
}

func (p *DatapowerProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		datasources.NewAAAJWTGeneratorDataSource,
		datasources.NewAAAJWTValidatorDataSource,
		datasources.NewAAAPolicyDataSource,
		datasources.NewAMQPBrokerDataSource,
		datasources.NewAMQPSourceProtocolHandlerDataSource,
		datasources.NewAPIApplicationTypeDataSource,
		datasources.NewAPIAuthURLRegistryDataSource,
		datasources.NewAPICORSDataSource,
		datasources.NewAPIClientIdentificationDataSource,
		datasources.NewAPICollectionDataSource,
		datasources.NewAPIConnectGatewayServiceDataSource,
		datasources.NewAPIDefinitionDataSource,
		datasources.NewAPIExecuteDataSource,
		datasources.NewAPIFinalDataSource,
		datasources.NewAPIGatewayDataSource,
		datasources.NewAPILDAPRegistryDataSource,
		datasources.NewAPIOperationDataSource,
		datasources.NewAPIPathDataSource,
		datasources.NewAPIPlanDataSource,
		datasources.NewAPIResultDataSource,
		datasources.NewAPIRoutingDataSource,
		datasources.NewAPIRuleDataSource,
		datasources.NewAPISchemaDataSource,
		datasources.NewAPISecurityDataSource,
		datasources.NewAPISecurityAPIKeyDataSource,
		datasources.NewAPISecurityBasicAuthDataSource,
		datasources.NewAPISecurityHTTPSchemeDataSource,
		datasources.NewAPISecurityOAuthDataSource,
		datasources.NewAPISecurityOAuthReqDataSource,
		datasources.NewAPISecurityRequirementDataSource,
		datasources.NewAPISecurityTokenManagerDataSource,
		datasources.NewAS1PollerSourceProtocolHandlerDataSource,
		datasources.NewAS2ProxySourceProtocolHandlerDataSource,
		datasources.NewAS2SourceProtocolHandlerDataSource,
		datasources.NewAS3SourceProtocolHandlerDataSource,
		datasources.NewAccessControlListDataSource,
		datasources.NewAccessProfileDataSource,
		datasources.NewAnalyticsEndpointDataSource,
		datasources.NewAppSecurityPolicyDataSource,
		datasources.NewAssemblyDataSource,
		datasources.NewAssemblyActionClientSecurityDataSource,
		datasources.NewAssemblyActionExtractDataSource,
		datasources.NewAssemblyActionFunctionCallDataSource,
		datasources.NewAssemblyActionGatewayScriptDataSource,
		datasources.NewAssemblyActionGraphQLCostAnalysisDataSource,
		datasources.NewAssemblyActionGraphQLExecuteDataSource,
		datasources.NewAssemblyActionGraphQLIntrospectDataSource,
		datasources.NewAssemblyActionHtmlPageDataSource,
		datasources.NewAssemblyActionInvokeDataSource,
		datasources.NewAssemblyActionJWTGenerateDataSource,
		datasources.NewAssemblyActionJWTValidateDataSource,
		datasources.NewAssemblyActionJson2XmlDataSource,
		datasources.NewAssemblyActionLogDataSource,
		datasources.NewAssemblyActionMapDataSource,
		datasources.NewAssemblyActionOAuthDataSource,
		datasources.NewAssemblyActionParseDataSource,
		datasources.NewAssemblyActionRateLimitDataSource,
		datasources.NewAssemblyActionRateLimitInfoDataSource,
		datasources.NewAssemblyActionRedactDataSource,
		datasources.NewAssemblyActionSetVarDataSource,
		datasources.NewAssemblyActionThrowDataSource,
		datasources.NewAssemblyActionUserSecurityDataSource,
		datasources.NewAssemblyActionValidateDataSource,
		datasources.NewAssemblyActionWSDLDataSource,
		datasources.NewAssemblyActionWebSocketUpgradeDataSource,
		datasources.NewAssemblyActionXSLTDataSource,
		datasources.NewAssemblyActionXml2JsonDataSource,
		datasources.NewAssemblyFunctionDataSource,
		datasources.NewAssemblyLogicOperationSwitchDataSource,
		datasources.NewAssemblyLogicSwitchDataSource,
		datasources.NewAuditLogDataSource,
		datasources.NewB2BCPADataSource,
		datasources.NewB2BCPACollaborationDataSource,
		datasources.NewB2BCPAReceiverSettingDataSource,
		datasources.NewB2BCPASenderSettingDataSource,
		datasources.NewB2BGatewayDataSource,
		datasources.NewB2BPersistenceDataSource,
		datasources.NewB2BProfileDataSource,
		datasources.NewB2BProfileGroupDataSource,
		datasources.NewB2BXPathRoutingPolicyDataSource,
		datasources.NewCORSPolicyDataSource,
		datasources.NewCORSRuleDataSource,
		datasources.NewCRLFetchDataSource,
		datasources.NewCertMonitorDataSource,
		datasources.NewCompileOptionsPolicyDataSource,
		datasources.NewCompileSettingsDataSource,
		datasources.NewConfigDeploymentPolicyDataSource,
		datasources.NewConfigSequenceDataSource,
		datasources.NewConformancePolicyDataSource,
		datasources.NewControlListDataSource,
		datasources.NewCookieAttributePolicyDataSource,
		datasources.NewCountMonitorDataSource,
		datasources.NewCryptoCertificateDataSource,
		datasources.NewCryptoFWCredDataSource,
		datasources.NewCryptoIdentCredDataSource,
		datasources.NewCryptoKerberosKDCDataSource,
		datasources.NewCryptoKerberosKeytabDataSource,
		datasources.NewCryptoKeyDataSource,
		datasources.NewCryptoSSKeyDataSource,
		datasources.NewCryptoValCredDataSource,
		datasources.NewDNSNameServiceDataSource,
		datasources.NewDeploymentPolicyParametersBindingDataSource,
		datasources.NewDistributedVariableDataSource,
		datasources.NewDocumentCryptoMapDataSource,
		datasources.NewDomainDataSource,
		datasources.NewDomainAvailabilityDataSource,
		datasources.NewDomainSettingsDataSource,
		datasources.NewDurationMonitorDataSource,
		datasources.NewEBMS2SourceProtocolHandlerDataSource,
		datasources.NewEBMS3SourceProtocolHandlerDataSource,
		datasources.NewErrorReportSettingsDataSource,
		datasources.NewFTPFilePollerSourceProtocolHandlerDataSource,
		datasources.NewFTPQuoteCommandsDataSource,
		datasources.NewFTPServerSourceProtocolHandlerDataSource,
		datasources.NewFileSystemUsageMonitorDataSource,
		datasources.NewFilterActionDataSource,
		datasources.NewFormsLoginPolicyDataSource,
		datasources.NewGWSRemoteDebugDataSource,
		datasources.NewGWScriptSettingsDataSource,
		datasources.NewGatewayPeeringDataSource,
		datasources.NewGatewayPeeringGroupDataSource,
		datasources.NewGatewayPeeringManagerDataSource,
		datasources.NewGitOpsDataSource,
		datasources.NewGitOpsTemplateDataSource,
		datasources.NewGitOpsVariablesDataSource,
		datasources.NewGraphQLSchemaOptionsDataSource,
		datasources.NewHTTPInputConversionMapDataSource,
		datasources.NewHTTPSSourceProtocolHandlerDataSource,
		datasources.NewHTTPSourceProtocolHandlerDataSource,
		datasources.NewHTTPUserAgentDataSource,
		datasources.NewHostAliasDataSource,
		datasources.NewImportPackageDataSource,
		datasources.NewIncludeConfigDataSource,
		datasources.NewInteropServiceDataSource,
		datasources.NewJOSERecipientIdentifierDataSource,
		datasources.NewJOSESignatureIdentifierDataSource,
		datasources.NewJSONSettingsDataSource,
		datasources.NewJWEHeaderDataSource,
		datasources.NewJWERecipientDataSource,
		datasources.NewJWSSignatureDataSource,
		datasources.NewKafkaClusterDataSource,
		datasources.NewKafkaSourceProtocolHandlerDataSource,
		datasources.NewLDAPConnectionPoolDataSource,
		datasources.NewLDAPSearchParametersDataSource,
		datasources.NewLoadBalancerGroupDataSource,
		datasources.NewLogLabelDataSource,
		datasources.NewLogTargetDataSource,
		datasources.NewLunaDataSource,
		datasources.NewLunaHAGroupDataSource,
		datasources.NewLunaHASettingsDataSource,
		datasources.NewLunaPartitionDataSource,
		datasources.NewMCFCustomRuleDataSource,
		datasources.NewMCFHttpHeaderDataSource,
		datasources.NewMCFHttpMethodDataSource,
		datasources.NewMCFHttpURLDataSource,
		datasources.NewMCFXPathDataSource,
		datasources.NewMPGWErrorActionDataSource,
		datasources.NewMPGWErrorHandlingPolicyDataSource,
		datasources.NewMQManagerDataSource,
		datasources.NewMQManagerGroupDataSource,
		datasources.NewMQv9PlusMFTSourceProtocolHandlerDataSource,
		datasources.NewMQv9PlusSourceProtocolHandlerDataSource,
		datasources.NewMTOMPolicyDataSource,
		datasources.NewMatchingDataSource,
		datasources.NewMessageContentFiltersDataSource,
		datasources.NewMessageMatchingDataSource,
		datasources.NewMessageTypeDataSource,
		datasources.NewMgmtInterfaceDataSource,
		datasources.NewMultiProtocolGatewayDataSource,
		datasources.NewNFSClientSettingsDataSource,
		datasources.NewNFSDynamicMountsDataSource,
		datasources.NewNFSFilePollerSourceProtocolHandlerDataSource,
		datasources.NewNFSStaticMountDataSource,
		datasources.NewNameValueProfileDataSource,
		datasources.NewOAuthProviderSettingsDataSource,
		datasources.NewOAuthSupportedClientDataSource,
		datasources.NewOAuthSupportedClientGroupDataSource,
		datasources.NewODRDataSource,
		datasources.NewODRConnectorGroupDataSource,
		datasources.NewOpenTelemetryDataSource,
		datasources.NewOpenTelemetryExporterDataSource,
		datasources.NewOpenTelemetrySamplerDataSource,
		datasources.NewOperationRateLimitDataSource,
		datasources.NewPOPPollerSourceProtocolHandlerDataSource,
		datasources.NewParseSettingsDataSource,
		datasources.NewPasswordAliasDataSource,
		datasources.NewPeerGroupDataSource,
		datasources.NewPolicyAttachmentsDataSource,
		datasources.NewPolicyParametersDataSource,
		datasources.NewProbeDataSource,
		datasources.NewProcessingMetadataDataSource,
		datasources.NewQuotaEnforcementServerDataSource,
		datasources.NewRADIUSSettingsDataSource,
		datasources.NewRBMSettingsDataSource,
		datasources.NewRaidVolumeDataSource,
		datasources.NewRateLimitConfigurationDataSource,
		datasources.NewRateLimitDefinitionDataSource,
		datasources.NewRateLimitDefinitionGroupDataSource,
		datasources.NewSAMLAttributesDataSource,
		datasources.NewSFTPFilePollerSourceProtocolHandlerDataSource,
		datasources.NewSLMActionDataSource,
		datasources.NewSLMCredClassDataSource,
		datasources.NewSLMPolicyDataSource,
		datasources.NewSLMRsrcClassDataSource,
		datasources.NewSLMScheduleDataSource,
		datasources.NewSMTPServerConnectionDataSource,
		datasources.NewSNMPSettingsDataSource,
		datasources.NewSOAPHeaderDispositionDataSource,
		datasources.NewSQLDataSourceDataSource,
		datasources.NewSSHClientProfileDataSource,
		datasources.NewSSHDomainClientProfileDataSource,
		datasources.NewSSHServerProfileDataSource,
		datasources.NewSSHServerSourceProtocolHandlerDataSource,
		datasources.NewSSHServiceDataSource,
		datasources.NewSSLClientProfileDataSource,
		datasources.NewSSLProxyServiceDataSource,
		datasources.NewSSLSNIMappingDataSource,
		datasources.NewSSLSNIServerProfileDataSource,
		datasources.NewSSLServerProfileDataSource,
		datasources.NewSchemaExceptionMapDataSource,
		datasources.NewSecureBackupModeDataSource,
		datasources.NewSocialLoginPolicyDataSource,
		datasources.NewStatelessTCPSourceProtocolHandlerDataSource,
		datasources.NewStatisticsDataSource,
		datasources.NewStylePolicyDataSource,
		datasources.NewStylePolicyActionDataSource,
		datasources.NewStylePolicyRuleDataSource,
		datasources.NewSystemSettingsDataSource,
		datasources.NewTAMDataSource,
		datasources.NewTCPProxyServiceDataSource,
		datasources.NewThrottlerDataSource,
		datasources.NewTimeSettingsDataSource,
		datasources.NewURLMapDataSource,
		datasources.NewURLRefreshPolicyDataSource,
		datasources.NewURLRewritePolicyDataSource,
		datasources.NewUserDataSource,
		datasources.NewUserGroupDataSource,
		datasources.NewVisibilityListDataSource,
		datasources.NewWCCServiceDataSource,
		datasources.NewWSEndpointRewritePolicyDataSource,
		datasources.NewWSGatewayDataSource,
		datasources.NewWSRRSavedSearchSubscriptionDataSource,
		datasources.NewWSRRServerDataSource,
		datasources.NewWSRRSubscriptionDataSource,
		datasources.NewWSStylePolicyDataSource,
		datasources.NewWSStylePolicyRuleDataSource,
		datasources.NewWXSGridDataSource,
		datasources.NewWebAppErrorHandlingPolicyDataSource,
		datasources.NewWebAppFWDataSource,
		datasources.NewWebAppRequestDataSource,
		datasources.NewWebAppResponseDataSource,
		datasources.NewWebAppSessionPolicyDataSource,
		datasources.NewWebB2BViewerDataSource,
		datasources.NewWebGUIDataSource,
		datasources.NewWebServiceMonitorDataSource,
		datasources.NewWebServicesAgentDataSource,
		datasources.NewWebSphereJMSServerDataSource,
		datasources.NewWebSphereJMSSourceProtocolHandlerDataSource,
		datasources.NewWebTokenServiceDataSource,
		datasources.NewXACMLPDPDataSource,
		datasources.NewXMLFirewallServiceDataSource,
		datasources.NewXMLManagerDataSource,
		datasources.NewXPathRoutingMapDataSource,
		datasources.NewXSLCoprocServiceDataSource,
		datasources.NewXSLProxyServiceDataSource,
		datasources.NewXTCProtocolHandlerDataSource,
		datasources.NewZosNSSClientDataSource,
	}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &DatapowerProvider{
			version: version,
		}
	}
}
